import type { NextConfig } from 'next'
const nextConfig: NextConfig = {
  images: { unoptimized: true },
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  },
  async rewrites() {
    return [
      {
        source: '/robots.txt',
        destination: '/api/robots',
      },
    ]
  },
  async redirects() {
    return [
    { source: '/products/milgo-cig-sut-2-lt', destination: '/urun/milgo-cig-sut-2l', permanent: true },
    { source: '/products/sade-tereyagi', destination: '/urun/sade-tereyagi', permanent: true },
    { source: '/products/sarimsakli-biberiyeli', destination: '/urun/sarimsakli-biberiyeli-tereyagi', permanent: true },
    { source: '/products/milgo-taze-surulebilir-laktozsuz', destination: '/urun/laktozsuz-peynir', permanent: true },
    { source: '/products/sade-peynir', destination: '/urun/sade-surullebilir-peynir', permanent: true },
    { source: '/products/milgo-pulbiberli-kekikli-tereyagi', destination: '/urun/sarimsakli-biberiyeli-tereyagi', permanent: true },
    { source: '/products/siyah-zeytinli-ve-kekikli', destination: '/urun/sade-surullebilir-peynir', permanent: true },
    { source: '/collections/all', destination: '/urunler', permanent: true },
    { source: '/collections/cig-sut', destination: '/kategoriler/cig-sut', permanent: true },
    { source: '/collections/peynir', destination: '/kategoriler/peynir', permanent: true },
    { source: '/collections/tereyagi', destination: '/kategoriler/tereyagi', permanent: true },
    { source: '/collections/tum-urunler', destination: '/urunler', permanent: true },
    { source: '/products/sarimsakli-kekikli', destination: '/urun/sade-surullebilir-peynir', permanent: true },
    { source: '/blogs/tarifler', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-cig-sut-ile-kakaolu-muhallebi', destination: '/blog/milgo-cig-sut-ile-kakaolu-muhallebi', permanent: true },
    { source: '/blogs/tarifler/milgo-cig-sut-ile-besamel-soslu-firin-makarna-tarifi', destination: '/blog/milgo-cig-sut-ile-besamel-soslu-firin-makarna-tarifi', permanent: true },
    { source: '/blogs/tarifler/milgo-cig-sut-ile-kremali-sebze-corbasi', destination: '/blog/milgo-cig-sut-ile-kremali-sebze-corbasi', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-limonlu-cheesecake-tarifi-ferah-hafif-ve-katkisiz-tatli', destination: '/blog/milgo-ile-limonlu-cheesecake-tarifi-ferah-hafif-ve-katkisiz-tatli', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-firinda-patlican-rulo-tarifi', destination: '/blog/milgo-ile-firinda-patlican-rulo-tarifi', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-sebzeli-peynirli-quesadilla-tarifi', destination: '/blog/milgo-ile-sebzeli-peynirli-quesadilla-tarifi', permanent: true },
    { source: '/blogs/tarifler/kremali-makarna', destination: '/blog/kremali-makarna', permanent: true },
    { source: '/blogs/tarifler/sarimsakli-kekikli-peynirli-pizza', destination: '/blog/sarimsakli-kekikli-peynirli-pizza', permanent: true },
    { source: '/blogs/tarifler/sarimsakli-kekikli-peynirli-zeytinyagli-kabak', destination: '/blog/sarimsakli-kekikli-peynirli-zeytinyagli-kabak', permanent: true },
    { source: '/blogs/tarifler/sade-tereyagi', destination: '/blog/sade-tereyagi', permanent: true },
    { source: '/blogs/tarifler/milgo-sade-tereyagi-ile-muhlama', destination: '/blog/milgo-sade-tereyagi-ile-muhlama', permanent: true },
    { source: '/blogs/tarifler/milgo-sade-tereyagi-ile-pancake', destination: '/blog/milgo-sade-tereyagi-ile-pancake', permanent: true },
    { source: '/blogs/tarifler/tuzlu-tereyagi-pirinc-pilavi', destination: '/blog/tuzlu-tereyagi-pirinc-pilavi', permanent: true },
    { source: '/blogs/tarifler/kruvasan', destination: '/blog/kruvasan', permanent: true },
    { source: '/blogs/tarifler/laktozsuz-peynirli-zucchini-noodles', destination: '/blog/laktozsuz-peynirli-zucchini-noodles', permanent: true },
    { source: '/blogs/tarifler/milgo-yaz-salatasi', destination: '/blog/milgo-yaz-salatasi', permanent: true },
    { source: '/blogs/tarifler/laktozsuz-peynirli-frittata', destination: '/blog/laktozsuz-peynirli-frittata', permanent: true },
    { source: '/blogs/tarifler/milgo-hurmali-smoothie', destination: '/blog/milgo-hurmali-smoothie', permanent: true },
    { source: '/blogs/tarifler/milgo-hurmali-tatli-kase', destination: '/blog/milgo-hurmali-tatli-kase', permanent: true },
    { source: '/blogs/tarifler/hurmali-cupcake', destination: '/blog/hurmali-cupcake', permanent: true },
    { source: '/blogs/tarifler/milgo-lu-bonfile-lezzeti', destination: '/blog/milgo-lu-bonfile-lezzeti', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah', destination: '/blog/milgo-ile-mutlu-sabah', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-1', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-2', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-3', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-4', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-5', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-6', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-7', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-8', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-ile-mutlu-sabah-9', destination: '/blog', permanent: true },
    { source: '/blogs/size-ozel-tarifler-milgo', destination: '/blog', permanent: true },
    { source: '/blogs/evde-dogallik-milgo-tereyaginin-hikayesi', destination: '/blog', permanent: true },
    { source: '/pages/contact', destination: '/iletisim', permanent: true },
    { source: '/pages/contact-1', destination: '/iletisim', permanent: true },
    { source: '/pages/abonelik', destination: '/abonelik', permanent: true },
    { source: '/pages/kullanim-kosullari', destination: '/', permanent: true },
    { source: '/collections/surulebilir-peynir-cesitleri', destination: '/kategoriler/peynir', permanent: true },
    { source: '/collections/tereyag', destination: '/kategoriler/tereyagi', permanent: true },
    { source: '/pages/gizlilik-politikasi', destination: '/gizlilik-politikasi', permanent: true },
    { source: '/pages/kvkk', destination: '/kvkk', permanent: true },
    { source: '/pages/uyelik-sozlesmesi', destination: '/mesafeli-satis', permanent: true },
    { source: '/pages/mesafeli-satis-sozlesmesi', destination: '/mesafeli-satis', permanent: true },
    { source: '/pages/keba-gida-iptal-iade-politikasi', destination: '/iade-politikasi', permanent: true },
    { source: '/blogs/tarifler/lavasli-tereyagli-mini-gozlemee', destination: '/blog', permanent: true },
    { source: '/blogs/tarifler/milgo-cig-sut-ile-sutlac', destination: '/blog', permanent: true },
    ]
  },
}
export default nextConfig
